# generated by cabal-rpm-2.1.0 --standalone
# https://docs.fedoraproject.org/en-US/packaging-guidelines/Haskell/

%global ghc_major 9.2
%global ghc_name ghc%{ghc_major}

%global ghc_without_dynamic 1
%global ghc_without_shared 1
%undefine with_ghc_prof
%undefine with_haddock
%global without_prof 1
%global without_haddock 1
%global debug_package %{nil}

Name:           pandoc-version
Version:        0.1.7
Release:        1%{?dist}
Summary:        One line summary

License:        BSD-3-Clause
Url:            https://hackage.haskell.org/package/%{name}
# Begin cabal-rpm sources:
Source0:        https://hackage.haskell.org/package/%{name}-%{version}/%{name}-%{version}.tar.gz
# End cabal-rpm sources

# Begin cabal-rpm deps:
BuildRequires:  ghc-rpm-macros
%if %{defined ghc_name}
BuildRequires:  %{ghc_name}-devel
BuildRequires:  %{ghc_name}-prof
BuildRequires:  zlib-devel
%else
BuildRequires:  ghc-base-devel
BuildRequires:  ghc-hslua-devel
%endif
BuildRequires:  cabal-install > 1.18
# End cabal-rpm deps

%description
Short paragraph here.


%prep
# Begin cabal-rpm setup:
%setup -q
# End cabal-rpm setup


%build
# Begin cabal-rpm build:
%global cabal_install %{_bindir}/cabal
%cabal_install update
%if 0%{?rhel} && 0%{?rhel} < 9
%cabal_install sandbox init
%cabal_install install
%endif
# End cabal-rpm build


%install
# Begin cabal-rpm install
mkdir -p %{buildroot}%{_bindir}
%if 0%{?fedora} >= 33 || 0%{?rhel} > 8
%if 0%{?fedora} >= 36
%ghc_set_gcc_flags
%endif
%cabal_install install -w ghc-%{ghc_major} --install-method=copy --enable-executable-stripping --installdir=%{buildroot}%{_bindir}
%else
for i in .cabal-sandbox/bin/*; do
strip -s -o %{buildroot}%{_bindir}/$(basename $i) $i
done
%endif
# End cabal-rpm install
%{buildroot}%{_bindir}/pandoc-version

%files
# Begin cabal-rpm files:
%license LICENSE
%{_bindir}/%{name}
# End cabal-rpm files


%changelog
* Fri Feb 24 2023 Jens Petersen <petersen@redhat.com> - 0.1.7-1
- spec file generated by cabal-rpm-2.1.0
